/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projekakhir;

import java.awt.Color;
import java.awt.Component;
import java.awt.Image;
import java.sql.Connection;
import java.sql.*;
import javax.swing.ImageIcon;
import java.util.Timer;
import java.util.TimerTask;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Lenovo
 */
public class User extends javax.swing.JFrame {
    private Timer timer;
    Connection conn = koneksi.getConnection();
    private int currentUserId;
    



  public User(int currentUserId) {
    initComponents();  // Menginisialisasi komponen GUI
    setKomponen();     // Panggilan metode untuk mengatur komponen tambahan
    setTampilan();     // Panggilan metode untuk mengatur tampilan
    loadProductData(1, jTextField2, jTextArea7, jTextField4, jTextField5, lblgambar);  // Memuat data untuk produk ID 1
    loadProductData(2, jTextField7, jTextArea8, jTextField31, jTextField32, lblgambar1);  // Memuat data untuk produk ID 2
    loadProductData(3, jTextField9, tadeskripsi, jTextField1, jTextField3, lblgambar2);
    loadProductData(4, jTextField10, jTextArea2, jTextField6, jTextField8, lblgambar4);
    loadProductData(5, jTextField11, jTextArea9, jTextField35, jTextField36, lblgambar5);
    loadProductData(6, jTextField12, jTextArea10, jTextField37, jTextField38, lblgambar6);
    loadProductData(11, jTextField13, jTextArea11, jTextField37, jTextField38, lblgambar3);
    loadProductData(13, jTextField12, jTextArea10, jTextField37, jTextField38, lblgambar7);
    tf1.setText("1");
    tf2.setText("1");
    tf3.setText("1");
    tf4.setText("1");
    tf5.setText("1");
    tf6.setText("1");
    this.currentUserId = currentUserId;

    // Contoh: Jika histori order lebih penting, muat itu dulu
    if (userTabbedPane.getSelectedIndex() == 4) {
        loadUserOrderHistory(currentUserId);
    }
    
    
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        blouse = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        userTabbedPane = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblgambar2 = new javax.swing.JLabel();
        lblgambar4 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tadeskripsi = new javax.swing.JTextArea();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jButton12 = new javax.swing.JButton();
        btnmin = new javax.swing.JButton();
        tf1 = new javax.swing.JTextField();
        tf2 = new javax.swing.JTextField();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        cb1 = new javax.swing.JCheckBox();
        cb2 = new javax.swing.JCheckBox();
        jButton2 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lblgambar = new javax.swing.JLabel();
        lblgambar1 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTextArea7 = new javax.swing.JTextArea();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jTextField31 = new javax.swing.JTextField();
        jTextField32 = new javax.swing.JTextField();
        jLabel54 = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        jTextArea8 = new javax.swing.JTextArea();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        tf3 = new javax.swing.JTextField();
        tf4 = new javax.swing.JTextField();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        cb3 = new javax.swing.JCheckBox();
        cb4 = new javax.swing.JCheckBox();
        jLabel55 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        lblgambar5 = new javax.swing.JLabel();
        lblgambar6 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jTextField35 = new javax.swing.JTextField();
        jTextField36 = new javax.swing.JTextField();
        jScrollPane10 = new javax.swing.JScrollPane();
        jTextArea9 = new javax.swing.JTextArea();
        jLabel63 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        jTextField37 = new javax.swing.JTextField();
        jTextField38 = new javax.swing.JTextField();
        jLabel65 = new javax.swing.JLabel();
        jScrollPane11 = new javax.swing.JScrollPane();
        jTextArea10 = new javax.swing.JTextArea();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        tf5 = new javax.swing.JTextField();
        tf6 = new javax.swing.JTextField();
        jButton24 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        cb5 = new javax.swing.JCheckBox();
        cb6 = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        jLabel66 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        lblgambar3 = new javax.swing.JLabel();
        lblgambar7 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        jTextField13 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jScrollPane12 = new javax.swing.JScrollPane();
        jTextArea11 = new javax.swing.JTextArea();
        jLabel68 = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        jTextField33 = new javax.swing.JTextField();
        jTextField34 = new javax.swing.JTextField();
        jLabel70 = new javax.swing.JLabel();
        jScrollPane13 = new javax.swing.JScrollPane();
        jTextArea12 = new javax.swing.JTextArea();
        jButton21 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        tf7 = new javax.swing.JTextField();
        tf8 = new javax.swing.JTextField();
        jButton27 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        jTextField15 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jTextField16 = new javax.swing.JTextField();
        cb7 = new javax.swing.JCheckBox();
        cb8 = new javax.swing.JCheckBox();
        jLabel71 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        userOrderTable = new javax.swing.JTable();
        jPanel11 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        aButton = new javax.swing.JButton();
        bButton = new javax.swing.JButton();
        cButton = new javax.swing.JButton();
        dButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        mainpanel = new javax.swing.JPanel();
        aPanel = new javax.swing.JPanel();
        aLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        bPanel = new javax.swing.JPanel();
        bLabel3 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        cPanel = new javax.swing.JPanel();
        cLabel3 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        dPanel = new javax.swing.JPanel();
        dLabel3 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        kembaliButton = new javax.swing.JButton();
        lanjutButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        userTabbedPane.setBackground(new java.awt.Color(255, 204, 255));

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Serif", 3, 18)); // NOI18N
        jLabel1.setText("ENOLA MERCH");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 160, -1));

        jLabel2.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        jLabel2.setText("MENYEDIAKAN MERCHENDASIE BAJU BAND");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, -1, -1));
        jPanel2.add(lblgambar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 220, 220));
        jPanel2.add(lblgambar4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 220, 240));

        jLabel4.setText("Stok :");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 280, -1, -1));

        jLabel10.setText("Harga :");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 310, -1, -1));

        jLabel11.setText("Deskripsi :");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 230, -1, -1));
        jPanel2.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 280, 150, -1));
        jPanel2.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 310, 150, -1));

        tadeskripsi.setColumns(20);
        tadeskripsi.setRows(5);
        jScrollPane1.setViewportView(tadeskripsi);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, 150, 60));

        jLabel13.setText("Stok :");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 530, -1, -1));

        jLabel14.setText("Harga :");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 560, -1, -1));
        jPanel2.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 530, 160, -1));
        jPanel2.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 560, 150, -1));

        jLabel15.setText("Deskripsi :");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 490, -1, -1));

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 460, 160, 60));

        jButton12.setText("+");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 340, -1, -1));

        btnmin.setText("-");
        btnmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnminActionPerformed(evt);
            }
        });
        jPanel2.add(btnmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 340, -1, -1));

        tf1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf1ActionPerformed(evt);
            }
        });
        jPanel2.add(tf1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 340, -1, -1));
        jPanel2.add(tf2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 590, -1, -1));

        jButton14.setText("-");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 590, -1, -1));

        jButton15.setText("+");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 590, -1, -1));

        jLabel16.setText("Nama :");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, -1, -1));
        jPanel2.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, 150, -1));

        jLabel17.setText("Nama :");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 430, -1, -1));
        jPanel2.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 430, 160, -1));

        cb1.setText("Pilih");
        cb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb1ActionPerformed(evt);
            }
        });
        jPanel2.add(cb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 370, -1, -1));

        cb2.setText("Pilih");
        jPanel2.add(cb2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 620, -1, -1));

        jButton2.setText("Kembali");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 730));

        userTabbedPane.addTab("Halaman 1", jPanel2);

        jPanel8.setBackground(new java.awt.Color(204, 204, 255));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Serif", 3, 18)); // NOI18N
        jLabel9.setText("ENOLA MERCH");
        jPanel8.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 140, -1));

        jLabel12.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        jLabel12.setText("MENYEDIAKAN MERCHENDASIE BAJU BAND");
        jPanel8.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, -1, -1));
        jPanel8.add(lblgambar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 200, 230));
        jPanel8.add(lblgambar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 190, 230));

        jLabel49.setText("Nama :");
        jPanel8.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, -1, -1));

        jLabel50.setText("Stok :");
        jPanel8.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 280, -1, -1));

        jLabel51.setText("Deskripsi :");
        jPanel8.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 230, -1, -1));
        jPanel8.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, 150, -1));
        jPanel8.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 280, 150, -1));

        jTextArea7.setColumns(20);
        jTextArea7.setRows(5);
        jScrollPane8.setViewportView(jTextArea7);

        jPanel8.add(jScrollPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, 150, 60));

        jLabel52.setText("Stok :");
        jPanel8.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 530, -1, -1));

        jLabel53.setText("Harga :");
        jPanel8.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 560, -1, -1));
        jPanel8.add(jTextField31, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 530, 150, -1));
        jPanel8.add(jTextField32, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 560, 150, -1));

        jLabel54.setText("Deskripsi :");
        jPanel8.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 490, -1, -1));

        jTextArea8.setColumns(20);
        jTextArea8.setRows(5);
        jScrollPane9.setViewportView(jTextArea8);

        jPanel8.add(jScrollPane9, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 460, 150, 60));

        jButton17.setText("+");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 340, -1, -1));

        jButton18.setText("-");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 340, -1, -1));

        tf3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf3ActionPerformed(evt);
            }
        });
        jPanel8.add(tf3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 340, -1, -1));
        jPanel8.add(tf4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 590, -1, -1));

        jButton19.setText("-");
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton19, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 590, -1, -1));

        jButton20.setText("+");
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton20, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 590, -1, -1));

        jLabel6.setText("Harga :");
        jPanel8.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 310, -1, -1));
        jPanel8.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 310, 150, -1));

        jLabel7.setText("Nama :");
        jPanel8.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 430, -1, -1));

        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });
        jPanel8.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 430, 150, -1));

        cb3.setText("Pilih");
        cb3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb3ActionPerformed(evt);
            }
        });
        jPanel8.add(cb3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 370, -1, -1));

        cb4.setText("Pilih");
        jPanel8.add(cb4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 620, -1, -1));
        jPanel8.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 730));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 564, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(71, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 725, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        userTabbedPane.addTab("Halaman 2", jPanel3);

        jPanel9.setBackground(new java.awt.Color(204, 204, 255));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel56.setFont(new java.awt.Font("Serif", 3, 18)); // NOI18N
        jLabel56.setText("ENOLA MERCH");
        jPanel9.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 140, -1));

        jLabel57.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        jLabel57.setText("MENYEDIAKAN MERCHENDASIE BAJU BAND");
        jPanel9.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, -1, -1));
        jPanel9.add(lblgambar5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 190, 230));
        jPanel9.add(lblgambar6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 170, 260));

        jLabel60.setText("Stok :");
        jPanel9.add(jLabel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 280, -1, -1));

        jLabel61.setText("Harga :");
        jPanel9.add(jLabel61, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 310, -1, -1));

        jLabel62.setText("Deskripsi :");
        jPanel9.add(jLabel62, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 230, -1, -1));
        jPanel9.add(jTextField35, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 280, 150, -1));
        jPanel9.add(jTextField36, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 310, 150, -1));

        jTextArea9.setColumns(20);
        jTextArea9.setRows(5);
        jScrollPane10.setViewportView(jTextArea9);

        jPanel9.add(jScrollPane10, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, 150, 60));

        jLabel63.setText("Stok :");
        jPanel9.add(jLabel63, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 530, -1, -1));

        jLabel64.setText("Harga :");
        jPanel9.add(jLabel64, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 560, -1, -1));
        jPanel9.add(jTextField37, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 530, 160, -1));
        jPanel9.add(jTextField38, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 560, 160, -1));

        jLabel65.setText("Deskripsi :");
        jPanel9.add(jLabel65, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 490, -1, -1));

        jTextArea10.setColumns(20);
        jTextArea10.setRows(5);
        jScrollPane11.setViewportView(jTextArea10);

        jPanel9.add(jScrollPane11, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 460, 160, 60));

        jButton22.setText("+");
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });
        jPanel9.add(jButton22, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 340, -1, -1));

        jButton23.setText("-");
        jButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton23ActionPerformed(evt);
            }
        });
        jPanel9.add(jButton23, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 340, -1, -1));

        tf5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf5ActionPerformed(evt);
            }
        });
        jPanel9.add(tf5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 340, -1, -1));
        jPanel9.add(tf6, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 590, -1, -1));

        jButton24.setText("-");
        jButton24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton24ActionPerformed(evt);
            }
        });
        jPanel9.add(jButton24, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 590, -1, -1));

        jButton25.setText("+");
        jButton25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton25ActionPerformed(evt);
            }
        });
        jPanel9.add(jButton25, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 590, -1, -1));

        jLabel18.setText("Nama :");
        jPanel9.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, -1, -1));
        jPanel9.add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, 150, -1));

        jLabel19.setText("Nama :");
        jPanel9.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 430, -1, -1));
        jPanel9.add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 430, 160, -1));

        cb5.setText("Pilih");
        cb5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb5ActionPerformed(evt);
            }
        });
        jPanel9.add(cb5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 370, -1, -1));

        cb6.setText("Pilih");
        cb6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb6ActionPerformed(evt);
            }
        });
        jPanel9.add(cb6, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 620, -1, -1));

        jButton1.setText("CheckOut");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel9.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 100, -1, -1));
        jPanel9.add(jLabel66, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 730));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(135, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 725, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        userTabbedPane.addTab("Halaman 3", jPanel5);

        jPanel10.setBackground(new java.awt.Color(204, 204, 255));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel20.setFont(new java.awt.Font("Serif", 3, 18)); // NOI18N
        jLabel20.setText("ENOLA MERCH");
        jPanel10.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 160, -1));

        jLabel21.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        jLabel21.setText("MENYEDIAKAN MERCHENDASIE BAJU BAND");
        jPanel10.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, -1, -1));
        jPanel10.add(lblgambar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 200, 240));
        jPanel10.add(lblgambar7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 200, 260));

        jLabel58.setText("Nama :");
        jPanel10.add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, -1, -1));

        jLabel59.setText("Stok :");
        jPanel10.add(jLabel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 280, -1, -1));

        jLabel67.setText("Deskripsi :");
        jPanel10.add(jLabel67, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 230, -1, -1));
        jPanel10.add(jTextField13, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, 150, -1));
        jPanel10.add(jTextField14, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 280, 150, -1));

        jTextArea11.setColumns(20);
        jTextArea11.setRows(5);
        jScrollPane12.setViewportView(jTextArea11);

        jPanel10.add(jScrollPane12, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, 150, 60));

        jLabel68.setText("Stok :");
        jPanel10.add(jLabel68, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 530, -1, -1));

        jLabel69.setText("Harga :");
        jPanel10.add(jLabel69, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 560, -1, -1));
        jPanel10.add(jTextField33, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 530, 150, -1));
        jPanel10.add(jTextField34, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 560, 150, -1));

        jLabel70.setText("Deskripsi :");
        jPanel10.add(jLabel70, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 490, -1, -1));

        jTextArea12.setColumns(20);
        jTextArea12.setRows(5);
        jScrollPane13.setViewportView(jTextArea12);

        jPanel10.add(jScrollPane13, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 460, 150, 60));

        jButton21.setText("+");
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });
        jPanel10.add(jButton21, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 340, -1, -1));

        jButton26.setText("-");
        jButton26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton26ActionPerformed(evt);
            }
        });
        jPanel10.add(jButton26, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 340, -1, -1));

        tf7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf7ActionPerformed(evt);
            }
        });
        jPanel10.add(tf7, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 340, -1, -1));
        jPanel10.add(tf8, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 590, -1, -1));

        jButton27.setText("-");
        jButton27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton27ActionPerformed(evt);
            }
        });
        jPanel10.add(jButton27, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 590, -1, -1));

        jButton28.setText("+");
        jButton28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton28ActionPerformed(evt);
            }
        });
        jPanel10.add(jButton28, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 590, -1, -1));

        jLabel22.setText("Harga :");
        jPanel10.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 310, -1, -1));
        jPanel10.add(jTextField15, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 310, 150, -1));

        jLabel23.setText("Nama :");
        jPanel10.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 430, -1, -1));

        jTextField16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField16ActionPerformed(evt);
            }
        });
        jPanel10.add(jTextField16, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 430, 150, -1));

        cb7.setText("Pilih");
        cb7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb7ActionPerformed(evt);
            }
        });
        jPanel10.add(cb7, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 370, -1, -1));

        cb8.setText("Pilih");
        jPanel10.add(cb8, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 620, -1, -1));
        jPanel10.add(jLabel71, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 730));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 510, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addGap(0, 5, Short.MAX_VALUE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 5, Short.MAX_VALUE)))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 730, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 725, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 641, Short.MAX_VALUE)
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel7Layout.createSequentialGroup()
                    .addGap(0, 65, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 66, Short.MAX_VALUE)))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 737, Short.MAX_VALUE)
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel7Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        userTabbedPane.addTab("Halaman 4", jPanel7);

        userOrderTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(userOrderTable);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(164, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(231, Short.MAX_VALUE))
        );

        userTabbedPane.addTab("Detail Pesanan", jPanel4);

        aButton.setText("Panel A");
        aButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aButtonActionPerformed(evt);
            }
        });

        bButton.setText(">>Panel B");
        bButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bButtonActionPerformed(evt);
            }
        });

        cButton.setText(">>Panel C");
        cButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cButtonActionPerformed(evt);
            }
        });

        dButton.setText(">>Panel D");
        dButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dButtonActionPerformed(evt);
            }
        });

        mainpanel.setLayout(new java.awt.CardLayout());

        aLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projekakhir/2-removebg-preview_21_11zon.jpg"))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("4.000 PEMBELIAN");

        javax.swing.GroupLayout aPanelLayout = new javax.swing.GroupLayout(aPanel);
        aPanel.setLayout(aPanelLayout);
        aPanelLayout.setHorizontalGroup(
            aPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aPanelLayout.createSequentialGroup()
                .addGroup(aPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(aPanelLayout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(aLabel3))
                    .addGroup(aPanelLayout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(293, Short.MAX_VALUE))
        );
        aPanelLayout.setVerticalGroup(
            aPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aPanelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(aLabel3)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        mainpanel.add(aPanel, "card2");

        bLabel3.setIcon(new javax.swing.ImageIcon("D:\\ENOLA\\3-removebg-preview_17_11zon.jpg")); // NOI18N

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel24.setText("3.000 PEMBELIAN");

        javax.swing.GroupLayout bPanelLayout = new javax.swing.GroupLayout(bPanel);
        bPanel.setLayout(bPanelLayout);
        bPanelLayout.setHorizontalGroup(
            bPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bPanelLayout.createSequentialGroup()
                .addGap(182, 182, 182)
                .addGroup(bPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bLabel3)
                    .addGroup(bPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(264, Short.MAX_VALUE))
        );
        bPanelLayout.setVerticalGroup(
            bPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(bLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel24)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        mainpanel.add(bPanel, "card3");

        cLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projekakhir/mdguns-removebg-preview_19_11zon.jpg"))); // NOI18N

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel25.setText("2.000 PEMBELIAN");

        javax.swing.GroupLayout cPanelLayout = new javax.swing.GroupLayout(cPanel);
        cPanel.setLayout(cPanelLayout);
        cPanelLayout.setHorizontalGroup(
            cPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cPanelLayout.createSequentialGroup()
                .addGap(174, 174, 174)
                .addGroup(cPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cLabel3))
                .addContainerGap(272, Short.MAX_VALUE))
        );
        cPanelLayout.setVerticalGroup(
            cPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(cLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel25)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        mainpanel.add(cPanel, "card4");

        dLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projekakhir/1_1_11zon-removebg-preview_22_11zon.jpg"))); // NOI18N
        dLabel3.setText("jLabel3");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("1.000 PEMBELIAN");

        javax.swing.GroupLayout dPanelLayout = new javax.swing.GroupLayout(dPanel);
        dPanel.setLayout(dPanelLayout);
        dPanelLayout.setHorizontalGroup(
            dPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dPanelLayout.createSequentialGroup()
                .addGap(145, 145, 145)
                .addGroup(dPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(301, Short.MAX_VALUE))
        );
        dPanelLayout.setVerticalGroup(
            dPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        mainpanel.add(dPanel, "card5");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addComponent(aButton, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bButton)
                        .addGap(18, 18, 18)
                        .addComponent(cButton)
                        .addGap(18, 18, 18)
                        .addComponent(dButton))
                    .addComponent(mainpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aButton)
                    .addComponent(bButton)
                    .addComponent(cButton)
                    .addComponent(dButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(mainpanel, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        kembaliButton.setText("<<");
        kembaliButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembaliButtonActionPerformed(evt);
            }
        });

        lanjutButton.setText(">>");
        lanjutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lanjutButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addGap(153, 153, 153)
                .addComponent(kembaliButton)
                .addGap(44, 44, 44)
                .addComponent(lanjutButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kembaliButton)
                    .addComponent(lanjutButton))
                .addContainerGap(287, Short.MAX_VALUE))
        );

        userTabbedPane.addTab("BestSeller", jPanel11);

        jPanel1.add(userTabbedPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 760));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


private void loadProductData(int idProduk, JTextField textFieldNama, JTextArea textAreaDeskripsi, JTextField textFieldStok, JTextField textFieldHarga, JLabel lblGambar) {
    String sql = "SELECT nama_produk, deskripsi, stok, harga, image_url FROM produk WHERE id_produk = ?";

    try (Connection conn = koneksi.getConnection();
         PreparedStatement pstmt = conn.prepareStatement(sql)) {

        pstmt.setInt(1, idProduk);  // Set ID produk sesuai yang dipilih

        try (ResultSet rs = pstmt.executeQuery()) {
            if (rs.next()) {
                // Mengisi data dari ResultSet ke komponen yang diberikan
                textFieldNama.setText(rs.getString("nama_produk"));
                textAreaDeskripsi.setText(rs.getString("deskripsi"));
                textFieldStok.setText(String.valueOf(rs.getInt("stok")));
                textFieldHarga.setText(String.valueOf(rs.getDouble("harga")));

                // Mengambil data gambar dan menampilkannya di JLabel
                byte[] imgData = rs.getBytes("image_url");
                if (imgData != null) {
                    ImageIcon productImage = new ImageIcon(imgData);
                    Image img = productImage.getImage().getScaledInstance(200, 300, Image.SCALE_SMOOTH);
                    lblGambar.setIcon(new ImageIcon(img));  // Menampilkan gambar di JLabel
                } else {
                    lblGambar.setIcon(null);  // Menangani kasus jika gambar tidak ditemukan
                    JOptionPane.showMessageDialog(this, "Gambar tidak ditemukan di database!");
                }
            } else {
                JOptionPane.showMessageDialog(this, "Data produk dengan ID " + idProduk + " tidak ditemukan!");
            }
        }
    } catch (SQLException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Terjadi kesalahan saat mengambil data: " + e.getMessage());
    }
}



private void updateStok(int idProduk, int jumlahBeli) {
    String querySelect = "SELECT stok FROM produk WHERE id_produk = ?";
    String queryUpdate = "UPDATE produk SET stok = ? WHERE id_produk = ?";

    try (Connection conn = koneksi.getConnection();
         PreparedStatement stmtSelect = conn.prepareStatement(querySelect);
         PreparedStatement stmtUpdate = conn.prepareStatement(queryUpdate)) {

        // Ambil stok saat ini
        stmtSelect.setInt(1, idProduk);
        ResultSet rs = stmtSelect.executeQuery();

        // Periksa apakah produk ditemukan
        if (rs.next()) {
            int stokSaatIni = rs.getInt("stok");

            // Validasi jumlah beli
            if (jumlahBeli <= 0) {
                JOptionPane.showMessageDialog(this, "Jumlah beli tidak valid.");
                return;
            }

            int stokBaru = stokSaatIni - jumlahBeli;

            // Periksa apakah stok mencukupi
            if (stokBaru >= 0) {
                // Update stok di database
                stmtUpdate.setInt(1, stokBaru);
                stmtUpdate.setInt(2, idProduk);
                int rowsAffected = stmtUpdate.executeUpdate();

                if (rowsAffected > 0) {
                    JOptionPane.showMessageDialog(this, "Pembelian berhasil untuk produk ID " + idProduk + ". Stok baru: " + stokBaru);
                } else {
                    JOptionPane.showMessageDialog(this, "Gagal memperbarui stok.");
                }
            } else {
                JOptionPane.showMessageDialog(this, "Stok tidak mencukupi untuk produk ID " + idProduk);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Produk dengan ID " + idProduk + " tidak ditemukan.");
        }

    } catch (SQLException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Terjadi kesalahan saat mengurangi stok: " + e.getMessage());
    }
}

private int createOrder(int userId, double totalPrice, String status) {
    String queryOrder = "INSERT INTO `orders` (user_id, total_price, order_status) VALUES (?, ?, ?)";
    System.out.println("Query Order: " + queryOrder);
    try (PreparedStatement stmtOrder = conn.prepareStatement(queryOrder, Statement.RETURN_GENERATED_KEYS)) {
        stmtOrder.setInt(1, userId);
        stmtOrder.setDouble(2, totalPrice);
        stmtOrder.setString(3, status);
        stmtOrder.executeUpdate();

        try (ResultSet generatedKeys = stmtOrder.getGeneratedKeys()) {
            if (generatedKeys.next()) {
                return generatedKeys.getInt(1);  // Mengembalikan order_id yang baru dibuat
            }
        }
    } catch (SQLException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Gagal membuat pesanan: " + e.getMessage());
    }
    return -1;
}

private void addOrderItem(int orderId, int productId, int quantity, double price) {
    String queryOrderItem = "INSERT INTO order_items (order_id, id_produk, quantity, price) VALUES (?, ?, ?, ?)";
    try (PreparedStatement stmtOrderItem = conn.prepareStatement(queryOrderItem)) {
        stmtOrderItem.setInt(1, orderId);    // Untuk kolom order_id
        stmtOrderItem.setInt(2, productId); // Untuk kolom id_produk
        stmtOrderItem.setInt(3, quantity);  // Untuk kolom quantity
        stmtOrderItem.setDouble(4, price);  // Untuk kolom price
        stmtOrderItem.executeUpdate();
        System.out.println("Item berhasil ditambahkan ke order_items.");
    } catch (SQLException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Gagal menambahkan item pesanan: " + e.getMessage());
    }
}





// Memanggil fungsi untuk produk dengan ID 1
private void loadDataForProduct1() {
    loadProductData(1, jTextField2, jTextArea7, jTextField4, jTextField5, lblgambar);
}

// Memanggil fungsi untuk produk dengan ID 2
private void loadDataForProduct2() {
    loadProductData(2, jTextField7, jTextArea8, jTextField31, jTextField32, lblgambar1);
}

private void loadDataForProduct3() {
    loadProductData(3, jTextField9, tadeskripsi, jTextField1, jTextField3, lblgambar2);
}

private void loadDataForProduct4() {
    loadProductData(4, jTextField10, jTextArea2, jTextField6, jTextField8, lblgambar4);
}

private void loadDataForProduct5() {
    loadProductData(5, jTextField11, jTextArea9, jTextField35, jTextField36, lblgambar5);
}

private void loadDataForProduct6() {
    loadProductData(6, jTextField12, jTextArea10, jTextField37, jTextField38, lblgambar6);
}


//tab riwayat orderan
private void loadUserOrderHistory(int userId) {
    DefaultTableModel model = (DefaultTableModel) userOrderTable.getModel(); // userOrderTable adalah JTable di tab histori order
    model.setRowCount(0); // Hapus data lama

    String sql = "SELECT order_item_id, order_id, product_id, quantity, price FROM order_items WHERE user_id = ?";
    try (PreparedStatement pstmt = conn.prepareStatement(sql)) {
        pstmt.setInt(1, userId);
        try (ResultSet rs = pstmt.executeQuery()) {
            while (rs.next()) {
                int orderItemId = rs.getInt("order_item_id");
                int orderId = rs.getInt("order_id");
                int productId = rs.getInt("product_id");
                int quantity = rs.getInt("quantity");
                double price = rs.getDouble("price");
                
                model.addRow(new Object[]{orderItemId, orderId, productId, quantity, price});
            }
        }
    } catch (SQLException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Gagal memuat histori order: " + e.getMessage());
    }
}
private void setKomponen(){
    arrPanel = new JPanel[] {aPanel,bPanel,cPanel,dPanel};
    arrButton = new JButton[] {aButton, bButton, cButton, dButton};
    arrColor = new Color[] {Color.RED,Color.ORANGE,Color.BLUE,Color.GREEN};
}
private void setTampilan() {
    for (int i = 0; i < arrPanel.length; i++) {
        arrButton[i].setBackground(arrColor[i]);
        arrButton[i].setForeground(Color.WHITE);

        if (i < panelPilihan) {
            arrButton[i].setVisible(true);
            arrPanel[i].setVisible(false);
        } else if (i == panelPilihan) {
            arrButton[i].setVisible(true);
            arrPanel[i].setBackground(arrColor[i]);
            arrPanel[i].setVisible(true);
        } else {
            arrButton[i].setVisible(false);
            arrPanel[i].setVisible(false);
        }
    }

    if (panelPilihan == 0) {
        kembaliButton.setEnabled(false);
        lanjutButton.setEnabled(true);
    } else if (panelPilihan == arrPanel.length - 1) {
        kembaliButton.setEnabled(true);
        lanjutButton.setEnabled(false);
    } else {
        kembaliButton.setEnabled(true);
        lanjutButton.setEnabled(true);
    }
}
    
    private void tf1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf1ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        int jumlah = Integer.parseInt(tf2.getText());
    if (jumlah > 1) {
        tf2.setText(String.valueOf(--jumlah));
    }
    }//GEN-LAST:event_jButton14ActionPerformed

    private void tf3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf3ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        int jumlah = Integer.parseInt(tf4.getText());
    if (jumlah > 1) {
        tf4.setText(String.valueOf(--jumlah));
    }
    }//GEN-LAST:event_jButton19ActionPerformed

    private void tf5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf5ActionPerformed

    private void jButton24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton24ActionPerformed
         int jumlah = Integer.parseInt(tf6.getText());
    if (jumlah > 1) {
        tf6.setText(String.valueOf(--jumlah));
    }
    }//GEN-LAST:event_jButton24ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        int Jumlah = Integer.parseInt(tf1.getText());
                Jumlah++; 
                tf1.setText(String.valueOf(Jumlah));
    }//GEN-LAST:event_jButton12ActionPerformed

    private void btnminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnminActionPerformed
         int jumlah = Integer.parseInt(tf1.getText());
    if (jumlah > 1) {
        tf1.setText(String.valueOf(--jumlah));
    }
    }//GEN-LAST:event_btnminActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        int Jumlah = Integer.parseInt(tf2.getText());
                Jumlah++; 
                tf2.setText(String.valueOf(Jumlah));
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
         int Jumlah = Integer.parseInt(tf3.getText());
                Jumlah++; 
                tf3.setText(String.valueOf(Jumlah));
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
         int jumlah = Integer.parseInt(tf3.getText());
    if (jumlah > 1) {
        tf3.setText(String.valueOf(--jumlah));
    }
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
       int Jumlah = Integer.parseInt(tf4.getText());
                Jumlah++; 
                tf4.setText(String.valueOf(Jumlah));
    }//GEN-LAST:event_jButton20ActionPerformed

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed
        int Jumlah = Integer.parseInt(tf5.getText());
                Jumlah++; 
                tf5.setText(String.valueOf(Jumlah));
    }//GEN-LAST:event_jButton22ActionPerformed

    private void jButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton23ActionPerformed
         int jumlah = Integer.parseInt(tf5.getText());
    if (jumlah > 1) {
        tf5.setText(String.valueOf(--jumlah));
    }
    }//GEN-LAST:event_jButton23ActionPerformed

    private void jButton25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton25ActionPerformed
        int Jumlah = Integer.parseInt(tf6.getText());
                Jumlah++; 
                tf6.setText(String.valueOf(Jumlah));
    }//GEN-LAST:event_jButton25ActionPerformed

    private void cb6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb6ActionPerformed

    private void cb3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb3ActionPerformed
        
    
    }//GEN-LAST:event_cb3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
JTextField[] jumlahFields = {tf1, tf2, tf3, tf4, tf5, tf6};  // TextField untuk jumlah pembelian masing-masing produk
    JCheckBox[] checkboxes = {cb1, cb2, cb3, cb4, cb5, cb6};      // Checkbox untuk memilih produk
    int[] productIds = {1, 2, 3, 4, 5, 6};                       // ID dari produk masing-masing checkbox

    double totalPrice = 0;
    try {
        for (int i = 0; i < checkboxes.length; i++) {
            if (checkboxes[i].isSelected()) {
                int idProduk = productIds[i];
                String jumlahText = jumlahFields[i].getText();
                if (jumlahText.isEmpty() || !jumlahText.matches("\\d+")) {
                    JOptionPane.showMessageDialog(this, "Masukkan jumlah pembelian yang valid pada produk " + (i + 1));
                    return;
                }
                int jumlahBeli = Integer.parseInt(jumlahText);

                // Ambil harga produk
                double hargaProduk = Double.parseDouble(jumlahFields[i].getText());
                totalPrice += hargaProduk * jumlahBeli;
                // Debugging sebelum update stok
                System.out.println("Updating stock for productId: " + idProduk + ", quantity: " + jumlahBeli);

                // Update stok produk
                updateStok(idProduk, jumlahBeli);
            }
        }

        // Membuat order baru
        int userId = 1;  // Sesuaikan dengan ID user yang sedang login
        int orderId = createOrder(userId, totalPrice, "Pending");
        
        // Debugging sebelum menambahkan item order
        System.out.println("Order created with orderId: " + orderId);

        // Menambahkan item order ke tabel order_item
        for (int i = 0; i < checkboxes.length; i++) {
            if (checkboxes[i].isSelected()) {
                int idProduk = productIds[i];
                int jumlahBeli = Integer.parseInt(jumlahFields[i].getText());
                double hargaProduk = Double.parseDouble(jumlahFields[i].getText());

                addOrderItem(orderId, idProduk, jumlahBeli, hargaProduk);
            }
        }

        JOptionPane.showMessageDialog(this, "Pesanan berhasil dibuat.");
//        // Menampilkan frame beli setelah pemesanan
//        new User(int currentUserId).setVisible(true);
//        this.dispose();

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Terjadi kesalahan: " + e.getMessage());
    }


    }//GEN-LAST:event_jButton1ActionPerformed


    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        new login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton21ActionPerformed

    private void jButton26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton26ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton26ActionPerformed

    private void tf7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf7ActionPerformed

    private void jButton27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton27ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton27ActionPerformed

    private void jButton28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton28ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton28ActionPerformed

    private void jTextField16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField16ActionPerformed

    private void cb7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb7ActionPerformed

    private void cb5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb5ActionPerformed

    private void cb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb1ActionPerformed

    private void bButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bButtonActionPerformed
        // TODO add your handling code here:
        panelPilihan =1;
        setTampilan();
    }//GEN-LAST:event_bButtonActionPerformed

    private void cButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cButtonActionPerformed
        // TODO add your handling code here:
        panelPilihan =3;
        setTampilan();
    }//GEN-LAST:event_cButtonActionPerformed

    private void dButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dButtonActionPerformed
        // TODO add your handling code here:
        panelPilihan =4;
        setTampilan();
    }//GEN-LAST:event_dButtonActionPerformed

    private void aButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aButtonActionPerformed
        // TODO add your handling code here:
        panelPilihan =0;
        setTampilan();
    }//GEN-LAST:event_aButtonActionPerformed

    private void kembaliButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembaliButtonActionPerformed
        // TODO add your handling code here:
        panelPilihan -=1;
        setTampilan();
    }//GEN-LAST:event_kembaliButtonActionPerformed

    private void lanjutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lanjutButtonActionPerformed
        // TODO add your handling code here:
         panelPilihan +=1;
        setTampilan();
    }//GEN-LAST:event_lanjutButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               new User(3).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aButton;
    private javax.swing.JLabel aLabel3;
    private javax.swing.JPanel aPanel;
    private javax.swing.JButton bButton;
    private javax.swing.JLabel bLabel3;
    private javax.swing.JPanel bPanel;
    private javax.swing.ButtonGroup blouse;
    private javax.swing.JButton btnmin;
    private javax.swing.JButton cButton;
    private javax.swing.JLabel cLabel3;
    private javax.swing.JPanel cPanel;
    private javax.swing.JCheckBox cb1;
    private javax.swing.JCheckBox cb2;
    private javax.swing.JCheckBox cb3;
    private javax.swing.JCheckBox cb4;
    private javax.swing.JCheckBox cb5;
    private javax.swing.JCheckBox cb6;
    private javax.swing.JCheckBox cb7;
    private javax.swing.JCheckBox cb8;
    private javax.swing.JButton dButton;
    private javax.swing.JLabel dLabel3;
    private javax.swing.JPanel dPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea jTextArea10;
    private javax.swing.JTextArea jTextArea11;
    private javax.swing.JTextArea jTextArea12;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea7;
    private javax.swing.JTextArea jTextArea8;
    private javax.swing.JTextArea jTextArea9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField31;
    private javax.swing.JTextField jTextField32;
    private javax.swing.JTextField jTextField33;
    private javax.swing.JTextField jTextField34;
    private javax.swing.JTextField jTextField35;
    private javax.swing.JTextField jTextField36;
    private javax.swing.JTextField jTextField37;
    private javax.swing.JTextField jTextField38;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JButton kembaliButton;
    private javax.swing.JButton lanjutButton;
    private javax.swing.JLabel lblgambar;
    private javax.swing.JLabel lblgambar1;
    private javax.swing.JLabel lblgambar2;
    private javax.swing.JLabel lblgambar3;
    private javax.swing.JLabel lblgambar4;
    private javax.swing.JLabel lblgambar5;
    private javax.swing.JLabel lblgambar6;
    private javax.swing.JLabel lblgambar7;
    private javax.swing.JPanel mainpanel;
    private javax.swing.JTextArea tadeskripsi;
    private javax.swing.JTextField tf1;
    private javax.swing.JTextField tf2;
    private javax.swing.JTextField tf3;
    private javax.swing.JTextField tf4;
    private javax.swing.JTextField tf5;
    private javax.swing.JTextField tf6;
    private javax.swing.JTextField tf7;
    private javax.swing.JTextField tf8;
    private javax.swing.JTable userOrderTable;
    private javax.swing.JTabbedPane userTabbedPane;
    // End of variables declaration//GEN-END:variables
 JPanel[] arrPanel;
    JButton[] arrButton;
    Color[] arrColor;
     
    int panelPilihan;
}
